### ISSUE TITLE
Light properties: State->state collapses after a second

### ISSUE THREAD

**Issue by Naharis** [Hyrules/WinHue#13]
Exact time varies, looks like a background update causes it to collapse again.
![winhue-20160825-2](https://cloud.githubusercontent.com/assets/9617215/17968387/d770fa02-6acc-11e6-84f4-b61b2b7251e3.png)

**Comment by Hyrules** [comment]
That might be related to the update the system does to the object. If you time it precisely it should be around 3 seconds. I'll see if there is anything I can do about this. This is not really a bug rather a side effect of an operation done on the light or other object.

**Comment by Hyrules** [comment]
This should be fixed in the next version.

**Comment by Hyrules** [comment]
This should be fixed in the latests version. Let me know if not.
