### ISSUE TITLE
Feature Request: Auto Refresh

### ISSUE THREAD

**Issue by FSSolution** [Hyrules/WinHue#192]
### Your setup 

WinHue version : (eg. 3.0.2838.0)
Bridge api version : (1.26)

### Expected behavior and actual behavior
Is it possible to add a auto refresh timer?

And a option to create an "if - then" method eg. light switched on after xxx seconds turn it off.

**Comment by Hyrules** [comment]
Adding an autorefresh option is possible and I had it in the past but it caused some odd behavior with some part of the program so I removed it. I'll see what I can do about it. As for the if - then solution your are looking at a rule. The rules are bridge objects that allow those types of actions. I have this implemented for the light in the laundry room. When the motion sensor detects motion, the lights turns on for 5 minutes and then turn off automatically. You don't need anything special in WinHue for this. Just an understanding of the rules. You will want to delay the condition of a rule.

Here is an example of the rule : 

`{
  "name": "MotionOff",
  "conditions": [{"address":"/sensors/7/state/presence","operator":"eq","value":"false"}, 
  {"address":"/sensors/7/state/lastupdated","operator":"ddx","value":**"PT00:05:00"**}],
  
"actions": [{"address":"/lights/13/state","method":"PUT","body":{"on":false,"transitiontime":0}},{"address":"/lights/17/state","method":"PUT","body":{"on":false,"transitiontime":0}}],
  "owner": "6K5DuLf2TawoU-JmUvBlTaZjJgV3MtR52AXf-8sr",
  "status": "enabled"
} `

Notice the PT00:05:00 this is the delay.

**Comment by Hyrules** [comment]
Auto refresh has been implemented in the latest version.
