### ISSUE TITLE
Detect bulb?

### ISSUE THREAD

**Issue by cw64** [Hyrules/WinHue#193]
Before submitting a request please make sure you are running the latest version of WinHue 
available in the release section of this site. Support will not be done on older version.

### Your setup 

WinHue version : 3.0.2338.0
Bridge api version : Don't know, where do I find this?
Light model : 9290012573A

### Expected behavior and actual behavior

Hub detects bulb

### Actual behavior

Hub doesn't detect bulb

### Steps to reproduce the problem

Turn Light on
Turn Hub on
Pair Hub

No bulb dectected.

Reading around seems to indicate that with newer generation bulbs the hub needs to told to dectect them. It will not find them automatically.

Update: More reading reveals that bulbs issued with starter kits are tied to the hub i.e. will not work with other hubs. The kit have is a refurb from amazon. Possibility that amazon have changed the bulb's/hub in this kit.

**Comment by Hyrules** [comment]
This is normal behavior. You need to search for new lights using the button on the main tool bar. in the search section first button on the left.

**Comment by cw64** [comment]
Can't, everything is unclickable

**Comment by Hyrules** [comment]
did you pair the bridge ?

**Comment by cw64** [comment]
Yes, I did successfully once, but it will not pair again.

**Comment by Hyrules** [comment]
if everything is greyed out it's because the pairing is not done. What do you have in the bridge paring windows ?

**Comment by cw64** [comment]
An icon, IP address and API key..

**Comment by Hyrules** [comment]
can you send me a log file here so i can take a look at it.

**Comment by cw64** [comment]
I should point out that I'm having to disconect the hub from the computer to connect to the internet.

**Comment by Hyrules** [comment]
The bridge needs to be connected to your local network and WinHue will not work remotely. Only in your local network.

**Comment by cw64** [comment]
I don't see a log file/folder there is log4net.config and log4net.dll you want these?

**Comment by Hyrules** [comment]
no you are not in the right folder. The log is not in WinHue folder in the program files folder it's in the appdata folder of your profile in Windows. open a explorer windows and type %appdata% you will see the WinHue folder at the bottom.

**Comment by cw64** [comment]
> 
> 
> The bridge needs to be connected to your local network and WinHue will not work remotely. Only in your local network.

My computer is my local network. Guess I'll be shipping this back to amazon too. Can't get LIFX to work, nor this, guess I'm not ment to have mood lighting.

**Comment by cw64** [comment]
[WinHue3 2018-09-19.txt](https://github.com/Hyrules/WinHue3/files/2398731/WinHue3.2018-09-19.txt)

**Comment by Hyrules** [comment]
You need a local network with a router to have WinHue or other lighting system working. I have lifx at home as well (Does not work with WinHue by the way) and philips hue needs to connect to the local network to work if you connect directly to a computer I'm not even sure it's possible to have it work. you would need at least a cross over cable you cannot connect a network cable directly to the hub from the computer it doesn't work like that.

**Comment by cw64** [comment]
sigh, thanks for your help.
