### ISSUE TITLE
Documentation fix request

### ISSUE THREAD

**Issue by adamlopresto** [Hyrules/WinHue#211]
whc shows the wrong options for sensors. Instead of showing the specific options for sensors, it shows the group options again. Looks like it should be a one-line fix (though I'm having trouble getting an environment to compile to test).

> diff --git a/whc/ConsoleHandler.cs b/whc/ConsoleHandler.cs
> index 7678701..ca90b3a 100644
> --- a/whc/ConsoleHandler.cs
> +++ b/whc/ConsoleHandler.cs
> @@ -1144,7 +1144,7 @@ namespace whc
>              GroupOpts.WriteOptionDescriptions(Console.Out);
>              Console.WriteLine("");
>              Console.WriteLine(@"\*\*\*\*\*\* SENSORS OPTIONS \*\*\*\*\*\*\*");
> \-            GroupOpts.WriteOptionDescriptions(Console.Out);
> \+            SensorOpts.WriteOptionDescriptions(Console.Out);
>              Console.WriteLine(@"\*\*\* Rules, sensors, scenes, schedules cannot be created by console. Please use WinHue 3 desktop application to create them. \*\*\*");
>              Console.WriteLine(@"\*\*\* You need to pair a bridge with WinHue gui before you send a command to the bridge for the first time.\*\*\*");
>          }

### Your setup 

WinHue version : (eg. 3.0.3367.0)

**Comment by Hyrules** [comment]
will take a look at this asap thanks for the report.

**Comment by Hyrules** [comment]
I have corrected this. Thanks for reporting it.

**Comment by Hyrules** [comment]
fixed in the latest version
