### ISSUE TITLE
transition

### ISSUE THREAD

**Issue by dasb00ter** [Hyrules/WinHue#212]
WinHue version : WinHue.3.0.3367.0.
Bridge api version : (1.28
Light model : (

### Expected behavior and actual behavior
Modify transition time of scenes made in hue app(not the preexisting scenes) and in scenes constructed on winhue3
...

### Actual behavior
Once I have made a scene in either the hue app or in your scene creator I cannot seem to alter the transition time. Do I have to do modify all the bulbs in the scene transition time. If I make a scene initially in winhue3 it works but if I subsequently try to edit it I lose the transition time. What the heck am I doing wrong during the editing process?

My goal was to create a dim scene and then a brighter version of that scene in the hue app. Then I would use winhue3 to edit the second scene with a transition time to make a nice fade in. I was going to use node red and home assistant for the scheduling . I have been at it a couple of hours now. Hope you can give me some direction. Essentially I am trying to edit the transition time of my own scene but its not sticking and I think I'm just not following the right procedure. Thanks alot for winhue3 being able to see the json in your app I think will help me understand some things latter on but for now I would just like to get this running 
...

**Comment by dasb00ter** [comment]
Appreciate if you can. When altering/editing a scene I'll select the bulb, make the changes to transition and, or, and without other changes to color etc then hit modify. This then always sets the transition to default no matter what I set. Ive tried different combinations of removing and readding the lights in the scene but this eventually causes a crash

**Comment by Hyrules** [comment]
I will take a look at this tomorrow evening. I will certainly have some things for you to test so stay close if you can.

**Comment by dasb00ter** [comment]
Sure I can give at go but working tomorrow night so maybe a day or two after that

**Comment by Hyrules** [comment]
definitly a bug there. I will fix it and send you a version to test soon.

**Comment by Hyrules** [comment]
It might be longer than anticipated. I'm having an issue with wpf toolkit which i'm using in WinHue. This library has a bug in it and I have to create a new control to get rid of this issue in order to fix the bug you have.

**Comment by Hyrules** [comment]
Here. You get a preview of the next version of WinHue. I have fixed the Scene editor. Don't forget to press the modify button if you edit a light of an already created scene (might try to change that sometime). Don't mind the transition field on the main form it doesn't disable when an object is not selected yet. Let me know what happens.

[WinHue 3.0.3676.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/2777187/WinHue.3.0.3676.0.Setup.zip)

**Comment by Hyrules** [comment]
should work in the lastest version
