### ISSUE TITLE
Keyboard Shortcuts no longer working in latest release

### ISSUE THREAD

**Issue by briman0094** [Hyrules/WinHue#214]
### Your setup 

WinHue version : (eg. 3.0.3367.0)
Bridge api version : (1.16)

### Expected behavior and actual behavior

Previously added keyboard shortcuts should still function reliably, and new keyboard shortcuts should be able to be configured and added.

### Actual behavior

Previous keyboard shortcuts stopped working reliably (would only affect some bulbs in a group, or wouldn't work at all). After deleting them, I'm unable to re-add them. I can fill out all the required information in the property grid, but clicking "Add" does nothing:

![image](https://user-images.githubusercontent.com/816612/51151636-1e295480-1831-11e9-91f4-7d7c9b86fe48.png)

### Steps to reproduce the problem

1) Delete all existing keyboard shortcuts
2) Attempt to add another one

**Comment by briman0094** [comment]
Upon exploring the source, it looks like this was possibly intentional, as the entire business logic for the hotkey creator was removed in a recent commit. Will this functionality be added back soon?

**Comment by Hyrules** [comment]
I don't remember why I commited this part of the code but i'll from what I see by unchecking it is the it gives me an duplicate error while adding a new hotkey. I will fix this in the next version.

**Comment by briman0094** [comment]
Made a quick PR since it's a simple fix in case you want to merge that

#215

**Comment by Hyrules** [comment]
Merge into the dev version.

**Comment by Turmire** [comment]
First and foremost, I just want to say I love this software and up until I updated to the most recent version I used it daily. Is there an ETA on the hotkey fix? The feature was really awesome and I'm not educated enough within the software/development field to fix my version, as stated above. Any info would be greatly appreciated.

**Comment by Hyrules** [comment]
check issue #212 there is a version of winhue with this fixed in it.

**Comment by Turmire** [comment]
Thank you @Hyrules !!!!

**Comment by Hyrules** [comment]
fixed in the latest version
