### ISSUE TITLE
Feature request - add option to 'Edit scenes' from the scene mapping view

### ISSUE THREAD

**Issue by erkr** [Hyrules/WinHue#216]
Hi
I really appreciate WinHUE as it offers a lot of tweaking that phone apps don't allow.
In my attempt to cleanup my scenes (some still have relocated lights included) a small Feature request:

The Scene Mapping view is great, but matching a particular scene in this view with the same scene in the main window is hard  (as multiple scenes have the same name)
Please add an option to open scene properties directly from the Scene Mapping view (in my case to select the 'Edit scene' option),

My WinHue version 3.0.3367.0

**Comment by Hyrules** [comment]
Sure can do. I will try to implement this in the next version.

**Comment by Hyrules** [comment]
this has been implemented in the latest version
