### ISSUE TITLE
64 bits only ?

### ISSUE THREAD

**Issue by Hyrules** [Hyrules/WinHue#223]
I was wondering if anyone still uses WinHue on 32 bits systems. 

Most systems nowaday are 64bits but some old one still run in 32 bits. I was thinging of compiling only in 64bits from now on. Any input would be appreciated from the users.

**Comment by banksio** [comment]
Personally I only use 64 bit systems as my main computers, which I think can be said for most people as the last decade of PCs have almost all been 64 bit. It would be nice to know for real if there was analytics on GitHub Pages or something.

**Comment by Hyrules** [comment]
I don't believe there is any analytics on github that's that precise but you are right. I've also been using a 64 bits os for the best part of the last decade ever since 4 gb of ram wasn't enough. I think I'll only compile WinHue in 64 bits from now on. I'm also thinking of moving to .net core as soon as the official version 3.0 is released. Right now it doesn't support WPF and Winforms but this should improve WinHue a little.

**Comment by banksio** [comment]
@Hyrules Nice, I like all of that. .NET Core sounds pretty good now they've added the GUIs and I think they're adding Windows 10 APIs for easily getting things like Windows 10 accent colour - should be good. Also just updated the readme for you. 😀
