### ISSUE TITLE
UI Lagging Heavily

### ISSUE THREAD

**Issue by banksio** [Hyrules/WinHue#224]
As per conversation in #219 - UI responding at about only 1fps when bridge objects on screen.

**Comment by Hyrules** [comment]
I have reverted to .net framework 4.5.2 and removed the transition time up down from the main form. You can see if this still cause the issue.

**Comment by Hyrules** [comment]
Looking at the log I can see that the initial load happens twice. That might be the reason it lags at start.

**Comment by Hyrules** [comment]
The latest dev version should load only once.

**Comment by banksio** [comment]
Just tried it but the lag is still there. Baffled.

I'm guessing light images are loading fine for you? Because I also don't know why they're not working for me.

Uploaded a short video to try and give you an idea of what I'm seeing. Hard to show when I'm actually clicking the mouse but should give you a bit of an idea. https://youtu.be/gZja-_hhuY0

**Comment by Hyrules** [comment]
hmm... ha... no your right the light are not loaded properly. It only loads the default light.

**Comment by banksio** [comment]
Also here's another video showing the rule creator which runs fine until I open the bridge objects dropdown - which makes me think the lag is something with the bridge objects... https://youtu.be/c2jBlq_n_wc

**Comment by Hyrules** [comment]
that's really odd. Ok I fixed the light not loading properly.

**Comment by banksio** [comment]
Alright yeah that's working great again, lag still there though. By the way the rule creator dropdowns are fine (apart from the lag) it's just the screen recorder I used didn't show them opening on the video.

I tried looking at the CPU Usage tab in the performance report but I couldn't find much.

**Comment by Hyrules** [comment]
If you select an object in the object selector in the rulecreator I get an exception. I understand why i'm fixing it now but the lag i'm still looking for the cause.

**Comment by banksio** [comment]
Ah OK I see. I'll keep looking at this lag.

**Comment by Hyrules** [comment]
if you disable the OnDeserialize method in the light.cs file does the lag still occur ?

Pihlips Hue -> HueObjects -> LightObject -> Light.cs line 140 to 146

**Comment by banksio** [comment]
Unfortunately yes it does.

**Comment by banksio** [comment]
I don't understand what is causing all the Layout updates.
![image](https://user-images.githubusercontent.com/30214760/54871210-8e5fd380-4da8-11e9-800a-a4e7ad69f95d.png)

**Comment by Hyrules** [comment]
try disabling the transition time control on line 428 of the MainWindow.xaml

**Comment by banksio** [comment]
No dice. For what it's worth the lag also happens in these creators: group, scene, schedule, hotkey (only when dropdown open) and resource link.

What's different about the floor plan creator? The listview there does not lag one bit (60fps smooth).

**Comment by Hyrules** [comment]
difference to my knowledge is that the main listview is not visible when it's visible...

**Comment by Hyrules** [comment]
The group creator has a listview. So does the scene creator and the main view. When you say the combo box in the hotkey creator which one the top one of the second one ?

**Comment by Hyrules** [comment]
Ok yeah I get the lag in the combobox in the hotkey creator. Second one.

**Comment by banksio** [comment]
Yeah, the one that lists all the stuff on the bridge.

**Comment by Hyrules** [comment]
hmmm could it be... let me check something...

**Comment by Hyrules** [comment]
OK here goes nothing. Try again with my latest push for the main view.

**Comment by banksio** [comment]
@Hyrules Will do in about fifteen mins

**Comment by banksio** [comment]
Bad news - hasn't solved it. I'm looking through each commit to try and find the commit that starts the lag.

**Comment by Hyrules** [comment]
There are so many commits between last version and this one that it may take a long time to find it.

**Comment by banksio** [comment]
Yeah, but might be the quickest way to find the source, I'm going to go 5 commits at a time at first then I can narrow it down. I'm getting some errors with commits around 1 Feb: 
![image](https://user-images.githubusercontent.com/30214760/54871945-4777db00-4db4-11e9-952a-00149c4839da.png)
Is this just a known issue with those commits (this is commit ad825214 with message Removed all reference to HueProperty not needed anymore. TODO : Preve…)

**Comment by Hyrules** [comment]
yeah there where some commit that didn't work or that wouldn't compile. Sometimes I start working on something and then commit and finish it at work so there might be some stuff that doesn't work

**Comment by banksio** [comment]
Alright found it: [this commit](https://github.com/Hyrules/WinHue/commit/840905d09ad19133640f2f0a9e1bd90232964081) is the last that works fine in terms of the lag.
[The next commit](https://github.com/Hyrules/WinHue/commit/7ce76f7f61b1b2b7d8e1a8a3795ad6cd336d0544) introduces the lag.

**Comment by Hyrules** [comment]
ok looking at it now.

**Comment by banksio** [comment]
Nice here's the comparison link it might help: https://github.com/Hyrules/WinHue/compare/840905d09ad19133640f2f0a9e1bd90232964081...7ce76f7f61b1b2b7d8e1a8a3795ad6cd336d0544

**Comment by Hyrules** [comment]
Ok try it again... i just commited a fix.

**Comment by banksio** [comment]
It's fixed!

**Comment by Hyrules** [comment]
I though so because the lag was gone in the hotkey creator ! Nice working finding the commit it gave me a hint.

**Comment by banksio** [comment]
No problem, glad I could help. Runs flawlessly in every creator now. What was causing the issue in the end?

**Comment by Hyrules** [comment]
In the serializer i was make a new Datacontract resolver every time I was serializing something. It must have created a choke somewhere. I remember seeing somewhere not to do what I was doing so I just move the creation to the root of the class and just assign the value every time I needed it instead.

**Comment by banksio** [comment]
Yeah it must've done something bad I guess your PC is so fast it felt barely different. Maybe I'll keep this laptop around when I upgrade to have a slower machine to test on!

**Comment by Hyrules** [comment]
Yeah if you want.

I will also create a virtual machine on my server here as well and limit the core speed and memory to see how WinHue reacts when I have those problems.

Actually ToString() seems to happen quite often. This might still slow stuff.

**Comment by banksio** [comment]
VM sounds like a good idea.
Yeah the lag I had felt like it ran multiple times a second.

**Comment by Hyrules** [comment]
Actually to stringis call virtually every time you click an object and multiple times. The propertygrid causes this. When it doesn't know how to display an object it will try to get the ToString method so it can show you text. Every expandable objects uses it so basically it's called alot.

**Comment by banksio** [comment]
Maybe a good idea to disable it when the propertygrid is hidden?

**Comment by Hyrules** [comment]
Yes that and the event viewer. They both run in the background until they are called.
