### ISSUE TITLE
Unhandled Exception 3.0.4301.0

### ISSUE THREAD

**Issue by Fulch** [Hyrules/WinHue#226]
Happens on launch, previous release was fine with same lights installed.
Log refers to MODELID : LCT015 as unknown, exception seems to happen straight after.
I have 2 of these and they are fairly recent UK model Hue White and Colour Ambience B22 fitting.
Hopefully log file is attached.
[WinHue3 2019-03-28.txt](https://github.com/Hyrules/WinHue/files/3017825/WinHue3.2019-03-28.txt)

**Comment by Hyrules** [comment]
I don't have any issue here with the 4301 version. Since I don't know the steps to reproduce this it's impossible to reproduce the bug for me. The log is simply not enough. I also don't have any json template for this light so I cannot tell what is happening.

**Comment by Hyrules** [comment]
Try this version and let me know hat happens
[WinHue 3.0.4312.0 Setup.zip](https://github.com/Hyrules/WinHue/files/3020369/WinHue.3.0.4312.0.Setup.zip)

**Comment by banksio** [comment]
@Hyrules Unfortunately I don't, although I am in the UK I haven't upgraded any of my colour bulbs. Hue is still expensive...

I was wondering if it is an issue with the light images code then it could be tested by deleting the files, but as you said the light images don't seem to be the issue here.

**Comment by Hyrules** [comment]
Odd because LCT015 is a standard Extended Color Light same as the first model LCT001. Anyway the error is not caused by the light in particular. it's caused by trying to remove some user hidden lights. The Index gets out or range when trying to remove it. WinHue should work even if the light is unknown. Only the bulb image will be default.

**Comment by Fulch** [comment]
Wow thank you for the fast fix.
Yes the 3.0.4312.0 version runs absolutely great!

Not sure that hidden objects is working for me now though, I mark a couple of objects as hidden then click save and done. Screen refreshes and hides the objects but if you check in Bridge Hidden Objects tab nothing is listed as being hidden and a further refresh restores those hidden objects. It appears as if the changes are not being saved?
This is not a big issue for me as I'm happy to have a working Winhue again.

**Comment by Hyrules** [comment]
Nice to hear. I will release a version this weekend because this might be breaking for some users. I'll try to fix the hidden object also.

**Comment by Hyrules** [comment]
Here. This version should fix the hidden object not working.

[WinHue 3.0.4316.0 Setup.zip](https://github.com/Hyrules/WinHue/files/3024495/WinHue.3.0.4316.0.Setup.zip)

**Comment by Fulch** [comment]
Just tested and yes hidden objects are now behaving correctly.

Thank you very much.
