### ISSUE TITLE
Rule Editor is entering invalid syntax into the script window

### ISSUE THREAD

**Issue by odelli** [Hyrules/WinHue#228]
Before submitting a request please make sure you are running the latest version of WinHue 
available in the release section of this site. Support will not be done on older version.

### Your setup 

WinHue version : 3.0.4316.0 (also tested 3.0.4301.0 which has the same bug)
Bridge api version : (1.29)

### Expected behavior and actual behavior
When working with the Rule Editor, the object types in the far left scroll list are supposed to be entered in <b>plural</b> and in <b>small letters</b> into the script, for example "lights", "groups", "sensors", etc.

### Actual behavior
Versions higher than 3.0.3367.0 is entering the object names in <b>singular</b>, and beginning with a <b>capital letter</b>.

![1](https://user-images.githubusercontent.com/30977267/55272953-0193a900-52c5-11e9-9df6-267968c600f8.PNG)

The resulting script is of course rejected by the Bridge.

![2](https://user-images.githubusercontent.com/30977267/55272954-06585d00-52c5-11e9-8b20-3174a4d6c6de.PNG)

### Steps to reproduce the problem

As shown in the screenshot, just start adding conditions and actions via the scroll lists for objects and elements the usual way you are supposed to work in the editor.

**Comment by Hyrules** [comment]
Oh sorry for the delay I don't understand why I missed your issue. I'll see what I can do here.

**Comment by Hyrules** [comment]
Here you go this should fix it. Let me know what happens.
[WinHue 3.0.4333.0 Setup.zip](https://github.com/Hyrules/WinHue/files/3031454/WinHue.3.0.4333.0.Setup.zip)

**Comment by odelli** [comment]
Hi,
I wouldn't call it "a delay", you probably have other things to do than watch this forum 24/7. So no worries.

Unfortunately, this version solved the problem with the capital letter issue, but the names are still in singular when they should be in plural.

![Annotation 2019-04-02 062725](https://user-images.githubusercontent.com/30977267/55376496-f208a000-5510-11e9-86fe-4c6e1f7203ea.png)

**Comment by Hyrules** [comment]
Yeah I wonder How I could miss that. Here the proper version. Pretty sure this one should work.

[WinHue 3.0.4334.0 Setup.zip](https://github.com/Hyrules/WinHue/files/3033482/WinHue.3.0.4334.0.Setup.zip)

**Comment by odelli** [comment]
It seems that the issue is solved in version 4334. I'm able to create rules with the correct syntax, and save them without any warning messages. Thanks for your time!

**Comment by Hyrules** [comment]
Nice to hear. I will release an official version to fix this.
