### ISSUE TITLE
User management not working anymore

### ISSUE THREAD

**Issue by SaturnusDJ** [Hyrules/WinHue#231]
WinHue version : 3.0.4334.0
Bridge api version : 1.31.0

Removing a user gives error: `Type : 1, unauthorized user at address /config/whitelist.`

I used an older version of WinHue before, and that got the same error.
Also, had to reinstall the iOS phone application Philips Hue in order to get access to the bridge again. Other integrations seemed to continue working but not error free, so also reconnected those.

My guess is that an update closed of the permissions to remove users.

**Comment by Hyrules** [comment]
I don't have this issue here. I can create and remove users without any problems. Note that i'm still on 1.29 and i'm not showing any update at the moment. Normally when you want to create a user you have to fill both field in the form and press the physical push button on the bridge before pressing the add button in WinHue.

**Comment by banksio** [comment]
For what it's worth, I'm also on API 1.31 and have the same issue (just checked). My bridge updated on the 2nd April.

Looks like Philips have changed the API keys format: 
![image](https://user-images.githubusercontent.com/30214760/55758731-844bff00-5a4f-11e9-8e17-bdee59c868fa.png)


I also noticed that you can no longer press the bridge button "virtually" anymore by POSTing to `/config/linkbutton`.

**Comment by Hyrules** [comment]
Odd I'll try to force an update and see what happens. As usual philips has not updated the API documentation.

**Comment by Hyrules** [comment]
Ok i'm now on 1.31 and i'm still not having this issue.

**Comment by Hyrules** [comment]
Well I have some bad news. This is not a bug. It's a new feature. You cannot remove user from the API anymore. You need to login here : https://account.meethue.com/apps to do it. I will remove the function to remove users as this wont work anymore.

**Comment by banksio** [comment]
That is annoying. Philips seem to be locking down the bridge's security at the moment. I suppose it's good from a security standpoint but don't really see the point.

Also they should have updated the API docs a bit earlier but hey ho.

**Comment by Hyrules** [comment]
I've written in the hue api forum. I find that stupid that I can create users without being online but I cannot delete them.

**Comment by banksio** [comment]
@Hyrules Thanks for the heads up, just replied there also. Hopefully Philips reconsider. They did with the third party bulbs update, so there's a chance they'll listen.

**Comment by zim514** [comment]
ditto
