### ISSUE TITLE
Can not use Group 0 in Rules

### ISSUE THREAD

**Issue by xIngenuusx** [Hyrules/WinHue#233]
WinHue version : 3.0.3443.0
Bridge api version : 1.31.0

Default group 0 (all lights) is not available (not displayed) to use in rules (conditions and actions)

**Comment by Hyrules** [comment]
Also fixed this one. I need to fix one last bug and I'll give you a new version to test.

**Comment by Hyrules** [comment]
Here you go. This version should correct the bugs you reported. Note that you cannot clone Entertainment groups at the moment.

[WinHue 3.0.4496.0 Setup.zip](https://github.com/Hyrules/WinHue/files/3154525/WinHue.3.0.4496.0.Setup.zip)
