### ISSUE TITLE
Rule Creator crashes when clicking on a time condition

### ISSUE THREAD

**Issue by banksio** [Hyrules/WinHue#234]
### Your setup 

WinHue version : 3.0.4434.0
Bridge api version : 1.31

### Expected behavior and actual behavior

Rule creator allows me to edit the condition when clicked.

### Actual behavior

WinHue crashes.

### Steps to reproduce the problem

1) Open a rule with a time condition
2) Click the time condition

[Log](https://pastebin.com/j1pXpSgD) (removed apikey and MAC).

**Comment by Hyrules** [comment]
something to do with the tree building a mismatch between number of params. i'll fix it.

**Comment by Hyrules** [comment]
You can try to pull the latest dev and see if you still have the issue. i'm pretty sure this is fixed but I will simple try to expand where the property is selected in another commit.

**Comment by banksio** [comment]
Hmm, unfortunately it's still crashing when I click the time condition. [Log](https://pastebin.com/eWPWG6Kv)

**Comment by Hyrules** [comment]
ok got it. I was able to emulate your bridge and see where it crashes.

**Comment by Hyrules** [comment]
You can go ahead and pull the latest dev version this should do it.

**Comment by banksio** [comment]
Yep that one's solved it! Nice work.

**Comment by banksio** [comment]
Alright, sorry looks like I was too hasty with that label @Hyrules - but it's a bit of a different issue. I just clicked on rule number 3 in my bridge (not sure if you need to emulate it again) and clicked on actions, there's an action to turn on a group and set the colour temperature. I removed the value from the ct box (I don't want it to be set), pressed add action and it crashed.

[Log](https://gist.github.com/banksio/c6d45002fd4fc85e0a36e2bcb6adeb20)

By the way I updated the screenshots on the website, I've got more plans for it but I've got exams at the moment so don't have time for a few weeks.

**Comment by Hyrules** [comment]
No problem. Yes I can replicate this is not the same error though. It's something else related to the path of the object.

**Comment by Hyrules** [comment]
Here you go.

[WinHue 3.0.4561.0 Setup.zip](https://github.com/Hyrules/WinHue/files/3224945/WinHue.3.0.4561.0.Setup.zip)

**Comment by banksio** [comment]
Thanks, that's fixed it! Is the "Do you want to replace this action?" new? I haven't seen it before but it's great.

**Comment by Hyrules** [comment]
Code was kinda commented. Forgot to add it back so I just uncommented it and added a few tweaks because the path was empty. I was also thinking of actually adding some test units to the program to test everything in order to catch bugs early. It's a long and boring job but it might avoid surprises.

**Comment by banksio** [comment]
Fair enough. Yeah adding some more tests might help, problem as you said though that it takes a while to test every single thing on the program. Luckily people on here are quite vigilant when it comes to spotting bugs.
