### ISSUE TITLE
To create a breathe sequence in a wave pattern for multiple lightbulbs

### ISSUE THREAD

**Issue by CraZyFelix** [Hyrules/WinHue#235]
I have a set of 17 Philips Hue lightbulbs, lined up horizontally from left to right. Say labeled 1-17.

Have been exploring the possibility of creating a set of rules with the following requirements:
1. Lightbulbs breathes (br from 26 to 254, with a transition time of 8 seconds) in a wave sequence (lightbulb 1 starts the breathing sequence first, then lightbulb 2 starts 1 second later, and lightbulb 3 starts 1 second after that)
2. The colour temperature would range from 500 on the left (lightbulb 1) to 153 on the right (lightbulb 17) (decrements of 21.7 in CT per bulb, rounded to the nearest integer)

I have done something with Philips Hue Labs' Meditation Lights Formula: https://labs.meethue.com/formulas/huelabs/meditation-lights

a. I am identified that rules named "9" is responsible for pushing a colour temperature number, but I am having trouble editing the number
b. Having trouble making the Meditation Lights breathing formula into a wave pattern

Any help would be appreciated.

**Comment by Hyrules** [comment]
I'm not an expert in rules. I don't really use them other than basically with the tap or Dimmer. If you want to make this wave breathing pattern you could get more help from the dev forum https://developers.meethue.com/forum/ other than that If you have an issue with WinHue I will need more to work with. Is there a crash or a bug somewhere. What do you do before it happens ?
