### ISSUE TITLE
Export datastore results in crash

### ISSUE THREAD

**Issue by joergenrasdk** [Hyrules/WinHue#237]
Before submitting a request please make sure you are running the latest version of WinHue 
available in the release section of this site. Support will not be done on older version.

### Your setup 

WinHue version : (eg. 3.0.4334)
Bridge api version : (1.31)
Light model : (if you have a problem with a particular light)

### Expected behavior and actual behavior

Tried "Export config", "Export full datastore".

### Actual behavior
A "Saveas" dialog box appears, file name is entered and error occurs:
![billede](https://user-images.githubusercontent.com/7330157/58459696-494f7900-812c-11e9-9ed6-3cc2209f2df3.png)

### Steps to reproduce the problem

1) ...
[log.zip](https://github.com/Hyrules/WinHue/files/3226126/log.zip)

2) ...
3) ...

In the case of a crash, please make sure to add a logfile containg the crash located in the %APPDATA%\WinHue3
to the issue you are opening.

**Comment by Hyrules** [comment]
Her you go fixed.
[WinHue 3.0.4567.0 Setup.zip](https://github.com/Hyrules/WinHue/files/3230100/WinHue.3.0.4567.0.Setup.zip)

**Comment by joergenrasdk** [comment]
Hi;

Seems to work OK now. Thank you for your prompt fix.

JørgenR.

 

 

Fra: Hyrules <notifications@github.com> 
Sendt: 29. maj 2019 01:29
Til: Hyrules/WinHue <WinHue@noreply.github.com>
Cc: joergenrasdk <joergenrasdk@gmail.com>; Author <author@noreply.github.com>
Emne: Re: [Hyrules/WinHue] Export datastore results in crash (#237)

 

Her you go fixed.
WinHue 3.0.4567.0 Setup.zip <https://github.com/Hyrules/WinHue/files/3230100/WinHue.3.0.4567.0.Setup.zip>
