### ISSUE TITLE
Winhue 3.0.4334 exception

### ISSUE THREAD

**Issue by Danimal8803** [Hyrules/WinHue#239]
Hi. 
After the latest update, I have the following issue preventing me to use my beloved Winhue. 

Any hints? Details see below. Happy to proivde more infos. 
Regards
Danny

Faulting application name: WinHue3.exe, version: 3.0.4334.0, time stamp: 0x5ca33940
Faulting module name: KERNELBASE.dll, version: 10.0.16299.820, time stamp: 0x917adac5
Exception code: 0xe0434352
Fault offset: 0x001045a2
Faulting process id: 0x358c
Faulting application start time: 0x01d5206d88131011
Faulting application path: C:\Apps\WinHue\WinHue3.exe

**Comment by Hyrules** [comment]
Need a log to debug. This windows event log does not help. There is a log file in WinHue folder in your windows profile.

**Comment by Danimal8803** [comment]
[WinHue3 2019-06-11.txt](https://github.com/Hyrules/WinHue/files/3282155/WinHue3.2019-06-11.txt)

**Comment by Danimal8803** [comment]
Hi. 
That is one of the latest logs. 
Thanks for your advice. 
Regards
Danny

**Comment by Hyrules** [comment]
can you try the release in #237 and send me the log if this still happens I have changed the part of the code that's crashing in your version.

**Comment by Danimal8803** [comment]
[WinHue3 2019-06-19.txt](https://github.com/Hyrules/WinHue/files/3305803/WinHue3.2019-06-19.txt)

**Comment by Danimal8803** [comment]
Hi.
No sucess yet with the version .4667. I have attached you another log. Maybe you can check it?
Thanks and regards
Danny

**Comment by Hyrules** [comment]
This line explain the problem : 

2019-06-19 13:06:23,249 [1] INFO  WinHue3.Functions.BridgeManager.BridgesManager [MoveNext:219] ==> Bridge update required. Please update the bridge to use WinHue with this bridge

Have you tried updating the bridge firmware ? this message is there for a reason WinHue is not backward compatible with old bridge version. Use the philips hue android app ou iphone app to update the bridge and try again.

**Comment by Danimal8803** [comment]
Thanks very much for your fast reply. Indeed, there was an update available. 
But even after the update (and there is nothing more in the app), the same error appears that the there is a update necessary. Any idea?

**Comment by Hyrules** [comment]
[WinHue 3.0.4686.0 Setup.zip](https://github.com/Hyrules/WinHue/files/3310002/WinHue.3.0.4686.0.Setup.zip)
Here is a version to test. I'm quite sure your issue is fixed. Let met know.

**Comment by Danimal8803** [comment]
Yes! Thank you very much. It works perfectly. 
So there was something in the bridge discovery routine that changed?

**Comment by Hyrules** [comment]
No in fact there was an error deseralizing lights. A condition was not check for null. So since you didn't had the archetype property on your light, there was an error when the app tried to deserialize the bridge and select the proper light image for your light.
