### ISSUE TITLE
Can't create a rule

### ISSUE THREAD

**Issue by erkr** [Hyrules/WinHue#243]
Hi

Just installed the lastest WinHue (thx for the updates!)
### My Setup 

WinHue version :   3.04666.0
Bridge api version : (1.32)
Bridge Sw Version : 1932073040

### The issue found:
Can't create a rule. When pressing save an error is raised (type-2, unknown error)
Tried to create several rules, all failed

### Screenshot
![image](https://user-images.githubusercontent.com/4363599/60127775-4f6b6080-9791-11e9-8599-b4bcfbd04a06.png)

**Comment by Hyrules** [comment]
this is a know issue. try the version in issue #242

**Comment by Hyrules** [comment]
I`ve just released a new version for this. You can download it in the release section.

**Comment by erkr** [comment]
Hi,

Thx for the blazing fast reply :-)
Installed the new version, now get another error. I create a rule for a motion temperature sensor. This is the condition:
![image](https://user-images.githubusercontent.com/4363599/60129704-e76b4900-9795-11e9-9ff5-fd6c147664a2.png)
Then I try to allert a group and get another error (type 4):
![image](https://user-images.githubusercontent.com/4363599/60129652-cacf1100-9795-11e9-880d-e80f3c787c69.png)

**Comment by Hyrules** [comment]
Yeah just made a fix for this release somehow I missed some code for the sync send http command so I was doing a put instead of a post. You can redownload the new release 4718 it should work properly.

**Comment by erkr** [comment]
Yes, it is fixed! Thx and have a Beer :-)
