### ISSUE TITLE
Crash when trying to add a hub

### ISSUE THREAD

**Issue by ajpanton** [Hyrules/WinHue#253]
Just installed the latest WinHue. Crashes with an exception as soon as I click "scan", or "Apply" after writing an IP manually.
[WinHue3 2019-09-26.txt](https://github.com/Hyrules/WinHue/files/3659749/WinHue3.2019-09-26.txt)

**Comment by ajpanton** [comment]
Worked around it by installing the 4666 version, paired the bridge there, and then upgraded to the latest 4718.

**Comment by Hyrules** [comment]
It's really odd. It looks like the thread has already started before you get the error. I'll take a look at this.

**Comment by Hyrules** [comment]
Can you tell me what version of the bridge firmware you are on ?

**Comment by ajpanton** [comment]
SW: 1934058060
This one?

**Comment by Hyrules** [comment]
no sorry my bad I meant the api version.

**Comment by ajpanton** [comment]
1.33.0

**Comment by Hyrules** [comment]
yes that should be good. I have the same version.

**Comment by Hyrules** [comment]
nevermind I just been able to reproduce your issue. I'll fix this.

**Comment by Hyrules** [comment]
fixed in the latest release.
