### ISSUE TITLE
Crash when going negative time

### ISSUE THREAD

**Issue by ajpanton** [Hyrules/WinHue#254]
When editing a scene, click a light, edit the transition time and go negative. Immediate crash.

Not a deal breaker, probably not even supported by the bridge (what would negative time even do?), but annoying when you accidentally press the down arrow and lose all changes you've made so far.
[WinHue3 2019-09-26.txt](https://github.com/Hyrules/WinHue/files/3659802/WinHue3.2019-09-26.txt)

**Comment by Hyrules** [comment]
Yes this one I have. I will fix this thanks for reporting it.

**Comment by Hyrules** [comment]
fixed in new release.
