### ISSUE TITLE
philips tap switch

### ISSUE THREAD

**Issue by JFg111** [Hyrules/WinHue#258]
I'm running the latest winhue version 3.04773.0
I don't own one of those spy-phone and don't intend into getting one for as long as we're not protected by privacy law. (Which will probably be, never.) So I've been using winhue for all my installation and tweaking of the hue lighting system in my house since using a spy-phone with an apps is out of the question. Everything is working great so far. BTW, thank you for this wonderful program.
However...
My question: Is there a way to use winhue to install a Philips tap switch?
I've tried the search for a new sensor icon and click on the button 3 on the tap switch for 10 seconds and did the same with the other buttons, but nothing is happening. Yes, I've been trying it 2 inches from the hub. I tried the manual way, but there is no way to find the address of the device + there is like no info on how to do it and what info to fill in the blank rectangle and in which format. 
If it's possible to install a tap switch using winhue program, could you please give us the instruction on how to do it.
The back of my tap switch has a model number plus what seems like a serial number under it, then there is "DC" written on the right of the tag, with the number 1642 under it.
Hope I'm not repeating a question that has already been asked by someone else. I did not find anything of help with the search function.
Thank you,

**Comment by Hyrules** [comment]
Actually I have never really tested the tap setup with WinHue. It's possible that It doesn't work. I will take a look at this. I have a tap here I can try to remove it and re add it. I'll try that tomorrow and let you know if this is an issue or not.

**Comment by Hyrules** [comment]
It's indeed not working. Now is it an issue with WinHue or the process itself. Again the philips hue api is crappy at best and form the way i'm understanding it WinHue is doing what it should now why isn't it working i'll try to find out.

**Comment by Hyrules** [comment]
Ha here you go it's working fine but the documentation is faulty again. To pair your tap do the following in WinHue go to the bridge settings window and note the bridge Zigbee channel. Start Searching for new sensors in WinHue then go near the bridge and press one of the following button for 10 sec ((button 1 = channel 11, 2 = chnl 15, 3 = chnl 20, 4 = chnl 25)). Wait a minute or refresh and your device should be there.

**Comment by JFg111** [comment]
Tanks. 
Tried it again and at the fifth try it finally worked. Does not seem to work every time.
The other day and all the previous time I tried, for some reason I never got it to work. That is why I did ask for your help. 
Now I finally have the tap icon in my sensor view. :-)
Tanks again!

**Comment by Hyrules** [comment]
Good to hear you are working. The tap is great because it does not have a battery but the button are really hit and miss. I can get them to work maybe 75% of the time. Sometime I have to mash the button 2 or 3 times before I get a response. I will mark this a closed.
