### ISSUE TITLE
You might want to make a little correction ...

### ISSUE THREAD

**Issue by JFg111** [Hyrules/WinHue#259]
On the code page and probably elsewhere you write:
PHILIPS HUE HAS RELEASED BLUETOOTH BULBS. WINHUE DOES NOT SUPPORT THOSE LIGHTS

You might want to change that to:
 PHILIPS HUE HAS RELEASED BLUETOOTH ENABLES HUE BULBS. WINHUE DOES NOT SUPPORT THAT NEW AND SEVERELY LIMITED MODE OF COMMUNICATION FOUND IN THOSE NEW HUE LIGHTS BULBS. HOWEVER, THOSE LIGHT BULBS ARE STILL HUE LIGHT BULBS AND WILL WORK JUST FINE WITH WINHUE, EXACTLY LIKE THE PREVIOUS NONE BLUETOOTH ENABLE HUE LIGHT BULBS. THE USE OF A BRIDGE IS MANDATORY AS IT IS THE COMPUTER THAT CONTROLS THE ENTIRE SYSTEM PERMITTING AUTOMATION. IT'S ALSO THE INTERFACE TO YOUR HOME ETHERNET AND Wi-Fi USED BY WINHUE, AND IT WILL PERMIT A FAR GREATER RANGE OF COVERAGE COMPARED TO BLUETOOTH. THE BRIDGE RANGE WILL USUALLY COVER AN ENTIRE REGULAR SIZE HOUSE IF NOT WAY MORE AS EACH ADDED LIGHT ACT LIKE A SIGNAL REPEATER EXTENDING THE RANGE EVEN FURTHER. AS FOR BLUETOOTH, IT IS QUITE SEVERELY RESTRICTED IN RANGE, TO ABOUT 15 FEET (ONE ROOM), AND IT WILL LIMIT YOUR CONTROL TO 10 LIGHT OR LESS. FINALLY, BLUETOOTH DOES NOT SUPPORT THE USE OF TIMERS.

**Comment by Hyrules** [comment]
Noted I will add this info to the readme. Thanks.

**Comment by Hyrules** [comment]
correction added.
