### ISSUE TITLE
renaming hub users

### ISSUE THREAD

**Issue by GravityRZ** [Hyrules/WinHue#269]
i know it is not possible anymore to delete users from winhue
you can do that by going to  the link https://account.meethue.com/apps

i however do not want to delete a user but to rename one.
the user was made while i had anfd iphone6 (thus the user is called iphone6-xxxxxxx)

i want to be able to rename the user
i can not delete the user and make a new one because i loose my scenes

**Comment by Hyrules** [comment]
I'll see if this is possible in the api. If so I will add it to the requested feature list.

**Comment by GravityRZ** [comment]
thanks. just tested with the ipad from my girlfriend. 
when you delete the app and install it again you need to pair with the bridge again.
it then creates a new user and leaves the scenes intact.

**Comment by Hyrules** [comment]
Yeah deleting the user is the only way to "rename" a user. One a user is created it's fixed in the bridge. There is no way of renaming them except deleting it from the official app or online and recreate them. Since It's not possible I will mark this a close.
