### ISSUE TITLE
Problem with HotkeyCreator: How can i delete a Hotkey?

### ISSUE THREAD

**Issue by Kulu-M** [Hyrules/WinHue#271]
Hello,

this program is wonderful! 

I am trying to set up simple hotkeys, for rising and lowering brightness of a certain room/group. Now I have 2 Hotkeys set up, but always both do the same. When i select one hotkey and change bri_inc to 50, the other also gets changed to 50.

Also I can't figure out how to delete a Hotkey? 

Thanks for any help.

**Comment by Hyrules** [comment]
Simply select a hotkey in the list and press delete on the keyboard ?

**Comment by Kulu-M** [comment]
Thanks, I did not try that.

Can I somehow decrease brightness with a hotkey? Setting it to a negative value changes the color instead of the brightness.

**Comment by Hyrules** [comment]
yes you need to use the bri_inc instead of bri and use a negative value. I have tested it here and it seem to be working fine.

**Comment by Kulu-M** [comment]
Ok, sadly this does not work for me. When I set a negativ value in bri_inc, the LEDs turn red and then off.

**Comment by Kulu-M** [comment]
nevermind, I made something wrong :)
