### ISSUE TITLE
reachable status

### ISSUE THREAD

**Issue by m-e-k-k-e-n** [Hyrules/WinHue#281]
Hi,
probably this is not an issue, it`s more an feature request.
I want to use the reachable status of a lamp to trigger some actions. The delay doesn`t matter at this point.
I tried to add it to a rule but it didn`t work. I could choose the status for the condition of the rule but when I want to save the rule, an error message appeared that I cannot use it.
Is there a reason that the reachable status cannot be used in a rule?
Cheers,
Ben

**Comment by Hyrules** [comment]
Most likely the bridge is simply not able to do that. Can you give me the message or a screenshot of the message I just want to confirm my theory. If you can do it in WinHue and the result message is an error it's because the bridge simply cannot do it.

**Comment by m-e-k-k-e-n** [comment]
Of course, I'll send you a scrennshot but it'll take some time.

**Comment by m-e-k-k-e-n** [comment]
I made a screenshot of condition, action and error. So you can see what I did. Is there a way to get the bridge checking on the reachable state? Maybe by a trick like using a sensor or so.

![condition](https://user-images.githubusercontent.com/61786068/76354653-2a188580-6313-11ea-9d57-10048f7d369f.JPG)

![action](https://user-images.githubusercontent.com/61786068/76354690-38ff3800-6313-11ea-81c0-70c5ace92f0d.JPG)

![error](https://user-images.githubusercontent.com/61786068/76354709-4288a000-6313-11ea-8ecc-bc713d8b7a30.JPG)

**Comment by Hyrules** [comment]
Yeah try adding a name to the rule at the top of the window.

**Comment by m-e-k-k-e-n** [comment]
Hehe yeah you`re right. I forgot to put the name in for the screenshots.
Before I did it with a name. I remember the error was same but it was /rules/condition instead of /rules/name. Is that possible?

**Comment by Hyrules** [comment]
Do you get this message : Type : 607 : Rule conditions contains errors or operator combination is not allowed at address /rules ?

**Comment by m-e-k-k-e-n** [comment]
I guess so. Need to doublecheck to be certain. Would that be a problem which cannot be bypassed?

**Comment by Hyrules** [comment]
Basically the bridge tells your that this combination of settings is not possible.

**Comment by m-e-k-k-e-n** [comment]
That's a shame. Would be great if the bridge could do it. I guess Philips just don't want the bridge to do it. Probably they want to sell their own switches instead of making everyone able to use the old switches.
Thanks for checking on it!

**Comment by Hyrules** [comment]
Unfortunately. I have confirmation from the dev forum that it's not possible. I have seen a post about the same thing your are asking and this is not possible.
