### ISSUE TITLE
Backup and restore of Hue bridge and objects configuration

### ISSUE THREAD

**Issue by Vuille** [Hyrules/WinHue#67]
Is there a simple way to backup and restore the whole Hue bridge and attached objects configuration?

**Comment by Hyrules** [comment]
Not to my knowledge. It has not been implemented in the Philips Hue API as of right now. Some people have asked for it to the devs.

**Comment by Vuille** [comment]
So, I do too ...

**Comment by Hyrules** [comment]
I could implement something... although it would require to have the exact same lights when restoring.

**Comment by Vuille** [comment]
A backup is needed in case of computer break down. Then obviously the configuration will not change and will be the same when restoring.

**Comment by Hyrules** [comment]
if your computer break down the bridge will still work and still be configured... adding a backup would be helpful in cases where you need to reset the bridge to a factory state for whatever reason.

**Comment by Vuille** [comment]
of course, you are right ... It does not change the issue, we can admit the lights configuration will not change meanwhile.

**Comment by Hyrules** [comment]
indeed.

**Comment by Hyrules** [comment]
It would be possible to get a dump of the datastore. I will try to add this as I believe that this is fairly easy to create. Can you make a request for a separate feature for this I will implement it.

**Comment by Hyrules** [comment]
I have it implemented in the next version. You will be able to get a copy of your settings from the bridge. This is a not a real backup system per se by it will allow you to get the current config of the bridge.

**Comment by Hyrules** [comment]
This has been implemented has store exportation.
